application: juthin
version: 5
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /writer/.*
  script: writer.py

- url: /twitter/tweet/
  script: writer.py

- url: /entry/sync/
  script: writer.py

- url: .*
  script: index.py

error_handlers:
- file: error.html

- error_code: over_quota
  file: error.html
